source "http://gems.rubyforge.org"

gem 'sinatra', '1.2.6'
gem 'rest-client', '1.6.1'
gem 'nokogiri', '1.4.1'
gem 'indextank', '1.0.9.1'
gem 'json', '1.5.1'
gem 'haml', :require => 'haml'
gem 'sass', :require => 'sass'
gem 'activesupport', '3.1.0'
gem 'activemodel', '3.1.0'
gem 'mongo', '1.4.0'
gem 'bson', '1.4.0'
gem 'bson_ext', '1.4.0'
gem 'mongo_mapper', '0.9.2'